'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';
import { ArrowLeft, Bookmark, CheckCircle2, ChevronRight, Eye, Loader2, RotateCcw, Search, XCircle } from 'lucide-react';
import toast from 'react-hot-toast';

type Row={id:string;question_number:number;question_type:string;question_html:string;options:any[];explanation_html:string;difficulty?:string|null;topic?:string|null;marks?:number|null;option_image_urls?:Record<string,string>;chapter?:{id:string;name:string;subject?:{id:string;name:string}};progress?:any};
function optionKey(o:any,i:number){return String(o?.key ?? o?.id ?? o?.value ?? i)}
function optionText(o:any){return String(o?.html ?? o?.text ?? o?.content ?? o?.label ?? (typeof o==='string'&&!/^(https?:|data:image\/)/i.test(o)?o:''))}
function optionImage(o:any,q:Row,i:number){const m:any=q.option_image_urls||{};const k=optionKey(o,i);const n=String.fromCharCode(65+i);const vals=[o?.imageUrl,o?.image_url,o?.src,typeof o?.image==='object'?(o.image.url||o.image.src):o?.image,m[k],m[String(i)],m[String(i+1)],m[n],m[n.toLowerCase()]];return String(vals.find(v=>typeof v==='string'&&v.trim())||'')}

export default function SavedQuestions(){
 const [rows,setRows]=useState<Row[]>([]); const [loading,setLoading]=useState(true); const [type,setType]=useState<'ALL'|'MCQ'|'MSQ'|'NAT'>('ALL'); const [attempted,setAttempted]=useState<'ALL'|'YES'|'NO'>('ALL'); const [search,setSearch]=useState(''); const [openSolution,setOpenSolution]=useState<string|null>(null);
 const load=async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){setLoading(false);return} const qs=new URLSearchParams();if(type!=='ALL')qs.set('type',type);if(attempted==='YES')qs.set('attempted','yes');if(attempted==='NO')qs.set('attempted','no');const res=await fetch(`/api/question-bank/saved?${qs}`,{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'});const d=await res.json();if(!res.ok){toast.error(d.error||'Unable to load saved questions.');return}setRows(d.questions||[]);setLoading(false)};
 useEffect(()=>{void load()},[type,attempted]);
 const visible=useMemo(()=>{const s=search.trim().toLowerCase();return rows.filter(q=>!s||String(q.question_html).replace(/<[^>]+>/g,' ').toLowerCase().includes(s)||q.chapter?.name?.toLowerCase().includes(s)||q.chapter?.subject?.name?.toLowerCase().includes(s)||String(q.question_number).includes(s))},[rows,search]);
 const unsave=async(q:Row)=>{const {data:{session}}=await supabase.auth.getSession();if(!session)return;const res=await fetch('/api/question-bank/attempt',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({questionId:q.id,action:'bookmark',value:false})});if(res.ok){setRows(v=>v.filter(x=>x.id!==q.id));toast.success('Question removed from Saved.')}else toast.error('Unable to unsave question.')};
 if(loading)return <div className="qb-theme min-h-[70vh] flex items-center justify-center text-slate-500"><Loader2 className="animate-spin mr-2"/>Loading saved questions…</div>;
 return <div className="qb-theme min-h-full bg-slate-50/70 text-slate-900"><div className="max-w-[1400px] mx-auto p-5 md:p-8 lg:p-10"><div className="flex items-center gap-3 mb-5"><Link href="/question-bank" className="inline-flex items-center gap-2 px-3 py-2 rounded-xl bg-white border border-slate-200 text-slate-600 shadow-sm"><ArrowLeft size={16}/>Question Bank</Link><div className="text-xs text-slate-400">/ Saved Questions</div></div>
 <section className="bg-white border border-slate-200 rounded-3xl p-5 md:p-6 shadow-sm mb-6"><div className="flex flex-wrap items-center gap-4"><div className="w-12 h-12 rounded-xl bg-amber-50 text-amber-600 flex items-center justify-center"><Bookmark size={22} fill="currentColor"/></div><div className="flex-1"><h1 className="text-2xl md:text-3xl font-black">Saved Questions</h1><p className="text-sm text-slate-500 mt-1">Your bookmarked questions from every subject.</p></div><div className="text-center"><div className="text-2xl font-black">{rows.length}</div><div className="text-[9px] font-black uppercase tracking-widest text-slate-400">Saved</div></div></div></section>
 <div className="flex flex-wrap gap-2 mb-4"><div className="flex flex-wrap gap-2">{(['ALL','MCQ','MSQ','NAT'] as const).map(v=><button key={v} onClick={()=>setType(v)} className={`px-3 py-2 rounded-xl text-xs font-black ${type===v?'bg-orange-500 text-white':'bg-white border border-slate-200 text-slate-500'}`}>{v==='ALL'?'All Types':v}</button>)}</div><div className="flex flex-wrap gap-2">{(['ALL','YES','NO'] as const).map(v=><button key={v} onClick={()=>setAttempted(v)} className={`px-3 py-2 rounded-xl text-xs font-black ${attempted===v?'bg-slate-800 text-white':'bg-white border border-slate-200 text-slate-500'}`}>{v==='ALL'?'All Attempts':v==='YES'?'Attempted':'Unattempted'}</button>)}</div><div className="flex items-center gap-2 bg-white border border-slate-200 rounded-xl px-3 py-2 ml-auto min-w-[220px]"><Search size={16} className="text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search saved questions…" className="bg-transparent outline-none text-sm flex-1"/></div></div>
 <div className="space-y-4">{visible.map(q=><article key={q.id} className="bg-white border border-slate-200 rounded-2xl shadow-sm p-5"><div className="flex items-start gap-3"><div className="flex-1"><div className="flex flex-wrap items-center gap-2 text-[10px] font-black uppercase tracking-wider text-slate-400"><span>{q.chapter?.subject?.name}</span><span>•</span><span>{q.chapter?.name}</span><span className="px-2 py-1 rounded-lg bg-slate-100 text-slate-600">{q.question_type}</span><span>Q{q.question_number}</span></div><div className="prose prose-slate max-w-none text-sm md:text-[15px] leading-6 mt-3 [&_img]:max-w-full [&_img]:h-auto [&_img]:rounded-lg" dangerouslySetInnerHTML={{__html:q.question_html||''}}/></div><button onClick={()=>void unsave(q)} title="Unsave" className="p-2 rounded-lg text-amber-600 bg-amber-50 hover:bg-amber-100"><Bookmark size={18} fill="currentColor"/></button></div>
 <div className="mt-4 flex flex-wrap gap-2">{q.question_type!=='NAT'&&(q.options||[]).map((o,i)=>{const img=optionImage(o,q,i);return <div key={i} className="flex-1 min-w-[180px] rounded-xl border border-slate-200 p-3 text-sm"><b className="mr-2">{String.fromCharCode(65+i)}</b>{optionText(o)}{img&&<img src={img} alt="" className="block max-w-full max-h-40 object-contain rounded mt-2"/>}</div>})}</div>
 <div className="mt-4 flex flex-wrap items-center gap-2"><Link href={`/question-bank/chapter/${q.chapter?.id}?questionId=${encodeURIComponent(q.id)}`} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-orange-500 text-white font-black text-sm">Attempt <ChevronRight size={16}/></Link><button onClick={()=>setOpenSolution(openSolution===q.id?null:q.id)} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-slate-100 text-slate-700 font-black text-sm"><Eye size={16}/>{openSolution===q.id?'Hide Solution':'View Solution'}</button>{q.progress?.attempted_count>0&&<span className="inline-flex items-center gap-1 text-xs font-bold text-emerald-600"><CheckCircle2 size={15}/>Attempted {q.progress.attempted_count}×</span>}</div>
 {openSolution===q.id&&<div className="mt-4 rounded-xl border border-orange-200 bg-orange-50/60 p-4"><div className="text-[10px] font-black uppercase tracking-widest text-orange-600 mb-2">Solution</div><div className="prose prose-slate max-w-none text-sm leading-6 [&_img]:max-w-full [&_img]:h-auto" dangerouslySetInnerHTML={{__html:q.explanation_html||'<p>No explanation available.</p>'}}/></div>}</article>)}{!visible.length&&<div className="py-20 text-center text-slate-500"><Bookmark className="mx-auto mb-3 opacity-40" size={32}/><div className="font-black">No saved questions found</div><div className="text-sm mt-1">Bookmark questions while practicing to see them here.</div></div>}</div>
 </div></div>
}
