'use client';

import { useEffect, useRef, useState } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { supabase } from '@/lib/supabase';
import { ArrowLeft, Check, CheckCircle2, ChevronLeft, ChevronRight, Loader2, Send, XCircle, Clock, RotateCcw } from 'lucide-react';
import toast from 'react-hot-toast';

type Q={id:string;question_number:number;question_type:string;question_html:string;options:any[];explanation_html:string;difficulty?:string|null;topic?:string|null;marks?:number|null;negative_marks?:number|null;image_urls?:string[];option_image_urls?:Record<string,string>;progress?:any};
function typeOf(q:Q){const t=String(q.question_type||'').toUpperCase();return ['NAT','INTEGER','NUMERIC'].includes(t)?'NAT':['MSQ','MULTI','MULTIPLE','MULTIPLE_CHOICE','MULTI_SELECT','MULTISELECT'].includes(t)?'MSQ':'MCQ'}
function optionHtml(o:any){return String(o?.html ?? o?.text ?? o?.content ?? o?.label ?? (typeof o==='string'?o:''))}
function optionKey(o:any,i:number){return String(o?.key ?? o?.id ?? o?.value ?? i)}
function optionImage(o:any,q:Q,i:number){const k=optionKey(o,i);const m=q.option_image_urls||{};return String([o?.imageUrl,o?.image_url,o?.image,o?.src,m[k],m[String(i)],m[String(i+1)],m[String.fromCharCode(65+i)]].find(v=>typeof v==='string'&&v.trim())||'')}

export default function RandomSession(){
 const params=useSearchParams(); const router=useRouter();
 const mode=(params.get('mode')==='test'?'test':'practice') as 'test'|'practice'; const chapters=params.get('chapters')||''; const count=Number(params.get('count')||20); const minutes=Number(params.get('minutes')||Math.max(count, count*2));
 const [questions,setQuestions]=useState<Q[]>([]); const [index,setIndex]=useState(0); const [answers,setAnswers]=useState<Record<string,string[]>>({}); const [results,setResults]=useState<Record<string,any>>({}); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false); const [remaining,setRemaining]=useState(minutes*60); const [finished,setFinished]=useState(false); const [score,setScore]=useState(0); const [submittedCount,setSubmittedCount]=useState(0); const contentRef=useRef<HTMLDivElement|null>(null);
 const q=questions[index]; const answer= q ? (answers[q.id]||[]) : [];
 const visible=questions;

 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){router.replace('/login');return} if(!chapters){toast.error('No chapters selected.');router.replace('/question-bank/randomize');return} const res=await fetch('/api/question-bank/random',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({chapterIds:chapters.split(',').filter(Boolean),count})});const d=await res.json();if(!res.ok){toast.error(d.error||'Unable to create random set.');router.replace('/question-bank/randomize');return}setQuestions(d.questions||[]);setLoading(false)})()},[chapters,count,router]);

 useEffect(()=>{if(mode!=='test'||loading||finished)return; if(remaining<=0){void finishTest(true);return} const id=window.setInterval(()=>setRemaining(v=>v-1),1000);return()=>window.clearInterval(id)},[mode,loading,finished,remaining]);
 useEffect(()=>{const root=contentRef.current;if(!root)return;const classify=()=>root.querySelectorAll('img').forEach((img)=>{const w=img.naturalWidth||img.getBoundingClientRect().width;const h=img.naturalHeight||img.getBoundingClientRect().height;img.classList.toggle('qb-large-image',w>=320||h>=180)});const imgs=Array.from(root.querySelectorAll('img'));imgs.forEach(img=>img.complete?classify():img.addEventListener('load',classify,{once:true}));classify();return()=>imgs.forEach(img=>img.removeEventListener('load',classify))},[q?.id]);

 const choose=(key:string)=>{if(!q||mode==='test'&&finished||results[q.id]||typeOf(q)==='NAT')return;setAnswers(p=>({...p,[q.id]:typeOf(q)==='MSQ'?(p[q.id]||[]).includes(key)?(p[q.id]||[]).filter(x=>x!==key):[...(p[q.id]||[]),key]:[key]}))};
 const setNat=(v:string)=>q&&setAnswers(p=>({...p,[q.id]:v.trim()? [v]:[]}));
 const submitPractice=async()=>{if(!q||results[q.id])return;if(!answer.length){toast.error(typeOf(q)==='NAT'?'Enter a numerical answer first.':'Select an answer first.');return} if(typeOf(q)==='NAT'&&!Number.isFinite(Number(answer[0]))){toast.error('Enter a valid number.');return}setSubmitting(true);try{const {data:{session}}=await supabase.auth.getSession();if(!session)return;const res=await fetch('/api/question-bank/attempt',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({questionId:q.id,answer})});const d=await res.json();if(!res.ok)throw new Error(d.error||'Submission failed');setResults(p=>({...p,[q.id]:d}))}catch(e:any){toast.error(e.message)}finally{setSubmitting(false)}};
 const finishTest=async(auto=false)=>{if(finished||submitting)return;setSubmitting(true);try{const {data:{session}}=await supabase.auth.getSession();if(!session)return;let total=0,done=0;for(const item of questions){const a=answers[item.id]||[];if(!a.length)continue;const res=await fetch('/api/question-bank/attempt',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({questionId:item.id,answer:a})});const d=await res.json();if(res.ok){done++;total+=Number(d.score||0);setResults(p=>({...p,[item.id]:d}))}}setScore(total);setSubmittedCount(done);setFinished(true);if(auto)toast.error('Time is up. Your answered questions were submitted.')}catch(e:any){toast.error(e.message)}finally{setSubmitting(false)}};
 const reset=()=>{setAnswers({});setResults({});setIndex(0);setFinished(false);setScore(0);setSubmittedCount(0);setRemaining(minutes*60)};
 const unanswered=questions.filter(x=>!(answers[x.id]||[]).length).length; const answered=questions.length-unanswered; const pct=questions.length?((index+1)/questions.length)*100:0; const fmt=(n:number)=>`${Math.floor(n/60).toString().padStart(2,'0')}:${(n%60).toString().padStart(2,'0')}`;

 if(loading)return <div className="qb-theme min-h-full flex items-center justify-center text-slate-500"><Loader2 className="animate-spin mr-2"/>Creating your random {mode}…</div>;
 if(finished)return <div className="qb-theme min-h-full bg-slate-50/70 text-slate-900"><div className="max-w-3xl mx-auto p-5 md:p-8"><div className="bg-white border border-slate-200 rounded-3xl shadow-sm p-7 md:p-10 text-center"><div className="w-16 h-16 mx-auto rounded-2xl bg-orange-50 text-orange-500 flex items-center justify-center"><CheckCircle2 size={32}/></div><div className="text-xs font-black uppercase tracking-[.25em] text-orange-500 mt-5">Random Test Complete</div><h1 className="text-3xl font-black mt-2">Your Result</h1><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-7"><Metric label="Questions" value={questions.length}/><Metric label="Answered" value={submittedCount}/><Metric label="Unanswered" value={questions.length-submittedCount}/><Metric label="Score" value={score}/></div><div className="flex flex-wrap justify-center gap-3 mt-7"><button onClick={reset} className="inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-orange-500 text-white font-black"><RotateCcw size={16}/>Try another attempt</button><button onClick={()=>router.push('/question-bank/randomize')} className="inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-white border border-slate-200 text-slate-700 font-black"><ShuffleIcon/>New random set</button></div></div></div></div>;

 return <div className="qb-theme min-h-full bg-slate-50/70 text-slate-900"><div className="max-w-7xl mx-auto p-3 md:p-6">
   <div className="flex flex-wrap items-center gap-3 mb-4"><button onClick={()=>router.push('/question-bank/randomize')} className="inline-flex items-center gap-2 px-3 py-2 rounded-xl bg-white border border-slate-200 text-slate-600 shadow-sm"><ArrowLeft size={16}/>Exit</button><div className="font-black text-lg">Random {mode==='test'?'Test':'Practice'}</div><div className="ml-auto flex items-center gap-4"><span className="text-xs font-bold text-slate-500">{answered}/{questions.length} answered</span>{mode==='test'&&<span className={`inline-flex items-center gap-2 px-3 py-2 rounded-xl font-black ${remaining<60?'bg-red-50 text-red-600':'bg-white border border-slate-200 text-slate-700'}`}><Clock size={16}/>{fmt(remaining)}</span>}</div></div>
   <div className="h-1.5 bg-slate-200 rounded-full overflow-hidden mb-4"><div className="h-full bg-orange-500" style={{width:`${pct}%`}}/></div>
   <div className="grid lg:grid-cols-[220px_1fr] gap-4">
    <aside className="bg-white border border-slate-200 rounded-2xl shadow-sm p-4 h-fit lg:sticky lg:top-4"><div className="text-xs font-black uppercase tracking-widest text-slate-400 mb-3">Question navigator</div><div className="grid grid-cols-5 gap-2">{questions.map((x,i)=>{const a=answers[x.id]?.length>0;const r=results[x.id];return <button key={x.id} onClick={()=>setIndex(i)} className={`h-9 rounded-lg text-xs font-black ${i===index?'bg-orange-500 text-white':r?.correct?'bg-emerald-50 text-emerald-700':r&&!r.correct?'bg-red-50 text-red-600':a?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-500'}`}>{i+1}</button>})}</div><div className="text-[11px] text-slate-400 mt-4">Random set: {questions.length} questions</div>{mode==='test'&&<button disabled={submitting} onClick={()=>void finishTest(false)} className="mt-4 w-full inline-flex items-center justify-center gap-2 py-2.5 rounded-xl bg-orange-500 text-white font-black disabled:opacity-50"><Send size={15}/>Submit Test</button>}</aside>
    <main className="bg-white border border-slate-200 rounded-2xl md:rounded-3xl shadow-sm overflow-hidden"><div className="px-5 md:px-8 py-4 border-b border-slate-100 flex flex-wrap gap-2 items-center"><span className="px-2.5 py-1 rounded-lg bg-slate-100 text-slate-600 text-[10px] font-black">{typeOf(q)}</span>{q.difficulty&&<span className="px-2.5 py-1 rounded-lg bg-amber-50 text-amber-700 text-[10px] font-black">{q.difficulty}</span>}{q.topic&&<span className="px-2.5 py-1 rounded-lg bg-slate-50 border border-slate-200 text-xs text-slate-500">{q.topic}</span>}<div className="ml-auto text-xs font-bold text-slate-400">Question {index+1} of {questions.length}</div></div>
      <div className="p-5 md:p-8 lg:p-10"><div ref={contentRef} className="qb-question-content prose prose-slate max-w-none text-[15px] md:text-base leading-7" dangerouslySetInnerHTML={{__html:q.question_html||''}}/>
       {typeOf(q)==='NAT'?<div className="mt-8 max-w-xl"><div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="font-black mb-3">Numerical Answer</div><input type="number" inputMode="decimal" step="any" disabled={Boolean(results[q.id])||finished} value={answer[0]||''} onChange={e=>setNat(e.target.value)} className="w-full h-14 px-4 rounded-xl border border-slate-300 bg-white text-lg font-bold outline-none focus:border-orange-400 disabled:bg-slate-100" placeholder="Enter numerical value"/></div></div>:<div className="mt-8 space-y-3">{(q.options||[]).map((o,i)=>{const key=optionKey(o,i),active=answer.includes(key),r=results[q.id],correctKey=r?.correctAnswer?.map(String).includes(key),html=optionHtml(o),img=optionImage(o,q,i);return <button key={key} disabled={Boolean(r)||finished} onClick={()=>choose(key)} className={`group w-full text-left p-4 md:p-5 rounded-2xl border-2 ${r&&correctKey?'border-emerald-400 bg-emerald-50':r&&active&&!correctKey?'border-red-300 bg-red-50':active?'border-orange-400 bg-orange-50':'border-slate-200 bg-white hover:border-slate-300'}`}><div className="flex gap-3 items-start"><span className={`w-8 h-8 shrink-0 rounded-full flex items-center justify-center text-xs font-black border-2 ${active?'bg-orange-500 border-orange-500 text-white':'border-slate-300 text-slate-500'}`}>{r&&correctKey?<Check size={15}/>:String.fromCharCode(65+i)}</span><div className="min-w-0 flex-1 prose prose-slate max-w-none text-sm leading-6" dangerouslySetInnerHTML={{__html:html}}/>{img&&!/<img\b/i.test(html)&&<img src={img} alt="" className="max-w-full max-h-64 object-contain rounded-lg"/>}</div></button>})}</div>}
       {results[q.id]&&<div className={`mt-8 rounded-2xl p-5 border ${results[q.id].correct?'border-emerald-200 bg-emerald-50/70':'border-red-200 bg-red-50/70'}`}><div className="flex items-center gap-3 font-black text-lg">{results[q.id].correct?<CheckCircle2 className="text-emerald-600"/>:<XCircle className="text-red-500"/>}{results[q.id].correct?'Correct':'Incorrect'}<span className="ml-auto text-sm text-slate-500">{results[q.id].score>0?`+${results[q.id].score}`:results[q.id].score} marks</span></div>{mode==='practice'&&<div className="mt-5 pt-5 border-t border-slate-200/80"><div className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-2">Explanation</div><div className="prose prose-slate max-w-none text-sm leading-6" dangerouslySetInnerHTML={{__html:q.explanation_html||'<p>No explanation available.</p>'}}/></div>}</div>}
      <div className="mt-8 pt-5 border-t border-slate-100 flex items-center gap-2"><button onClick={()=>setIndex(Math.max(0,index-1))} disabled={index===0} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-white border border-slate-200 font-black disabled:opacity-30"><ChevronLeft size={17}/>Previous</button>{mode==='practice'&&<button disabled={Boolean(results[q.id])||submitting} onClick={()=>void submitPractice()} className="ml-auto inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-orange-500 text-white font-black disabled:opacity-40">{submitting?<Loader2 size={16} className="animate-spin"/>:<Send size={16}/>}Submit Answer</button>}<button onClick={()=>setIndex(Math.min(questions.length-1,index+1))} disabled={index===questions.length-1} className={`${mode==='practice'?'':'ml-auto'} inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-white border border-slate-200 font-black disabled:opacity-30`}>Next<ChevronRight size={17}/></button></div>
     </div></main>
   </div>
 </div></div>
}
function Metric({label,value}:{label:string;value:number|string}){return <div className="rounded-xl bg-slate-50 border border-slate-100 p-3"><div className="text-xl font-black">{value}</div><div className="text-[9px] uppercase font-black tracking-wider text-slate-400">{label}</div></div>}
function ShuffleIcon(){return <span aria-hidden="true">↻</span>}
