'use client';

import Link from 'next/link';
import { ArrowLeft, BarChart3, Clock3, Moon, Save, Settings2, SunMedium } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../lib/supabase';
import { getISTDateString } from '../../../lib/dataService';
import toast from 'react-hot-toast';

type SleepRow = { date_str: string; bed_time: string | null; wake_time: string | null; night_sleep_minutes: number; afternoon_sleep_minutes: number; masturbation: boolean | null };
const fmt = (m:number) => { const h=Math.floor(m/60), min=Math.round(m%60); return h ? `${h}h${min ? ` ${min}m`:''}` : `${min}m`; };
const nightMinutes = (bed:string,wake:string) => { if(!bed||!wake) return 0; const [bh,bm]=bed.split(':').map(Number),[wh,wm]=wake.split(':').map(Number); let a=bh*60+bm,b=wh*60+wm; if(b<=a)b+=1440; return b-a; };
const hours=(m:number)=>Math.round((m/60)*10)/10;

export default function SleepTrackerPage(){
 const today=getISTDateString();
 const [enabled,setEnabled]=useState(false),[trackMast,setTrackMast]=useState(false),[rows,setRows]=useState<SleepRow[]>([]);
 const [bed,setBed]=useState(''),[wake,setWake]=useState(''),[nap,setNap]=useState('0'),[mast,setMast]=useState(''),[range,setRange]=useState<7|30|90>(30);
 const [study,setStudy]=useState<Record<string,number>>({}),[saving,setSaving]=useState(false),[settingsSaving,setSettingsSaving]=useState(false);
 const load=async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session)return;const [{data:p},{data:s},{data:d}]=await Promise.all([
  supabase.from('user_profiles').select('sleep_tracking_enabled,track_masturbation').eq('user_id',session.user.id).maybeSingle(),
  supabase.from('sleep_tracking').select('date_str,bed_time,wake_time,night_sleep_minutes,afternoon_sleep_minutes,masturbation').eq('user_id',session.user.id).order('date_str',{ascending:false}).limit(365),
  supabase.from('daily_tracking').select('date_str,study_minutes').eq('user_id',session.user.id).order('date_str',{ascending:false}).limit(365)
 ]);setEnabled(!!p?.sleep_tracking_enabled);setTrackMast(!!p?.track_masturbation);setRows((s||[]) as SleepRow[]);const r=(s||[]).find(x=>x.date_str===today);if(r){setBed(r.bed_time?.slice(0,5)||'');setWake(r.wake_time?.slice(0,5)||'');setNap(String(r.afternoon_sleep_minutes||0));setMast(r.masturbation==null?'':r.masturbation?'yes':'no')}const sm:Record<string,number>={};(d||[]).forEach(x=>sm[x.date_str]=Number(x.study_minutes||0));setStudy(sm);};
 useEffect(()=>{load()},[]);
 const toggle=async(e:boolean,m=trackMast)=>{const {data:{session}}=await supabase.auth.getSession();if(!session)return;setSettingsSaving(true);const {error}=await supabase.from('user_profiles').update({sleep_tracking_enabled:e,track_masturbation:m}).eq('user_id',session.user.id);setSettingsSaving(false);if(error)toast.error(error.message);else{setEnabled(e);setTrackMast(m);toast.success(e?'Sleep tracking enabled':'Sleep tracking disabled')}};
 const save=async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session)return;if(!bed||!wake){toast.error('Enter bedtime and wake time.');return}setSaving(true);const {error}=await supabase.from('sleep_tracking').upsert({user_id:session.user.id,date_str:today,bed_time:bed,wake_time:wake,night_sleep_minutes:nightMinutes(bed,wake),afternoon_sleep_minutes:Math.max(0,Number(nap)||0),masturbation:trackMast?(mast===''?null:mast==='yes'):null},{onConflict:'user_id,date_str'});setSaving(false);if(error)toast.error(error.message);else{toast.success('Sleep saved');load()}};
 const chart=useMemo(()=>{const end=new Date(`${today}T12:00:00`);end.setDate(end.getDate()-(range-1));const map=new Map(rows.map(r=>[r.date_str,r]));return Array.from({length:range},(_,i)=>{const d=new Date(end);d.setDate(end.getDate()+i);const date=getISTDateString(d),r=map.get(date);return {date, sleep:(r?.night_sleep_minutes||0)+(r?.afternoon_sleep_minutes||0), study:study[date]||0}})},[rows,study,range,today]);
 const max=Math.max(8,...chart.map(x=>Math.max(hours(x.sleep),hours(x.study)))),W=1000,H=340,px=58,py=28,iw=W-px*2,ih=H-py*2;
 const pts=(key:'sleep'|'study')=>chart.map((r,i)=>`${px+(i/(Math.max(1,chart.length-1)))*iw},${H-py-(hours(r[key])/max)*ih}`).join(' ');
 const labels=chart.filter((_,i)=>i%Math.max(1,Math.floor(chart.length/7))===0);
 const todayRow=rows.find(r=>r.date_str===today);
 return <div className="min-h-screen bg-[#050505] text-zinc-300 p-4 md:p-8"><div className="max-w-[1200px] mx-auto space-y-6">
  <div className="flex items-start justify-between gap-4"><div><Link href="/dashboard" className="text-[9px] uppercase tracking-widest text-zinc-500 hover:text-zinc-200 flex items-center gap-1 mb-3"><ArrowLeft size={12}/> Dashboard</Link><h1 className="text-2xl sm:text-3xl font-black text-zinc-100">Sleep & Recovery</h1><p className="text-xs text-zinc-500 mt-1">Simple manual sleep tracking alongside your study hours.</p></div><div className="px-3 py-2 rounded-xl bg-zinc-900/60 ring-1 ring-zinc-800 text-[9px] font-black uppercase tracking-widest"><Moon size={13} className="inline text-indigo-400 mr-2"/>{enabled?'Tracking On':'Tracking Off'}</div></div>
  <section className="grid lg:grid-cols-2 gap-5">
   <div className="bg-zinc-900/50 ring-1 ring-zinc-800 rounded-3xl p-5"><div className="flex items-center gap-2 mb-4"><Settings2 size={16} className="text-indigo-400"/><h2 className="font-black text-zinc-100">Tracking Settings</h2></div><div className="flex items-center justify-between p-4 rounded-2xl bg-zinc-950/70 ring-1 ring-zinc-800"><div><div className="text-sm font-bold text-zinc-200">Track daily sleep</div><div className="text-[10px] text-zinc-600 mt-1">When enabled, the app will ask for your daily sleep record.</div></div><button disabled={settingsSaving} onClick={()=>toggle(!enabled)} className={`w-12 h-7 rounded-full p-1 ${enabled?'bg-indigo-500':'bg-zinc-800'}`}><span className={`block w-5 h-5 rounded-full bg-white transition-transform ${enabled?'translate-x-5':''}`}/></button></div>{enabled&&<div className="mt-3 flex items-center justify-between p-4 rounded-2xl bg-zinc-950/70 ring-1 ring-zinc-800"><div><div className="text-sm font-bold text-zinc-200">Ask about masturbation</div><div className="text-[10px] text-zinc-600 mt-1">Optional private morning question.</div></div><button disabled={settingsSaving} onClick={()=>toggle(enabled,!trackMast)} className={`w-12 h-7 rounded-full p-1 ${trackMast?'bg-rose-500':'bg-zinc-800'}`}><span className={`block w-5 h-5 rounded-full bg-white transition-transform ${trackMast?'translate-x-5':''}`}/></button></div>}</div>
   <div className="bg-zinc-900/50 ring-1 ring-zinc-800 rounded-3xl p-5"><div className="flex items-center gap-2 mb-4"><Clock3 size={16} className="text-emerald-400"/><h2 className="font-black text-zinc-100">Today • {today}</h2></div><div className="grid grid-cols-2 gap-3"><label className="text-[9px] uppercase tracking-widest text-zinc-500">Bed time<input type="time" value={bed} onChange={e=>setBed(e.target.value)} className="mt-1 w-full bg-zinc-950 ring-1 ring-zinc-800 rounded-xl px-3 py-2.5 text-sm text-zinc-100"/></label><label className="text-[9px] uppercase tracking-widest text-zinc-500">Wake time<input type="time" value={wake} onChange={e=>setWake(e.target.value)} className="mt-1 w-full bg-zinc-950 ring-1 ring-zinc-800 rounded-xl px-3 py-2.5 text-sm text-zinc-100"/></label><label className="text-[9px] uppercase tracking-widest text-zinc-500">Afternoon sleep (min)<input type="number" min="0" value={nap} onChange={e=>setNap(e.target.value)} className="mt-1 w-full bg-zinc-950 ring-1 ring-zinc-800 rounded-xl px-3 py-2.5 text-sm text-zinc-100"/></label>{trackMast&&<label className="text-[9px] uppercase tracking-widest text-zinc-500">Masturbation<select value={mast} onChange={e=>setMast(e.target.value)} className="mt-1 w-full bg-zinc-950 ring-1 ring-zinc-800 rounded-xl px-3 py-2.5 text-sm text-zinc-100"><option value="">Choose</option><option value="yes">Yes</option><option value="no">No</option></select></label>}</div><div className="mt-4 flex items-center justify-between gap-3 text-xs text-zinc-500">Night <b className="text-zinc-200">{fmt(nightMinutes(bed,wake))}</b> • Total <b className="text-emerald-400">{fmt(nightMinutes(bed,wake)+(Number(nap)||0))}</b><button onClick={save} disabled={!enabled||saving} className="ml-auto px-4 py-2.5 rounded-xl bg-emerald-500 text-zinc-950 font-black text-[9px] uppercase tracking-widest disabled:opacity-30"><Save size={13} className="inline mr-1"/>{saving?'Saving':'Save'}</button></div></div>
  </section>
  <section className="bg-zinc-900/50 ring-1 ring-zinc-800 rounded-3xl p-5 sm:p-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-5"><div><div className="flex items-center gap-2"><BarChart3 size={16} className="text-indigo-400"/><h2 className="font-black text-zinc-100">Sleep + Study Hours</h2></div><p className="text-[10px] text-zinc-600 mt-1">Daily sleep (night + afternoon) compared with GATE study time.</p></div><div className="flex gap-1 bg-zinc-950 rounded-xl p-1 ring-1 ring-zinc-800">{([7,30,90] as const).map(n=><button key={n} onClick={()=>setRange(n)} className={`px-3 py-1.5 rounded-lg text-[9px] font-black ${range===n?'bg-indigo-500 text-white':'text-zinc-500'}`}>{n===7?'7 DAYS':n===30?'AUG/SEP/…':'3 MONTHS'}</button>)}</div></div><div className="overflow-x-auto"><svg viewBox={`0 0 ${W} ${H}`} className="w-full min-w-[720px] h-[300px]"><line x1={px} x2={px} y1={py} y2={H-py} stroke="currentColor" className="text-zinc-800"/>{[0,2,4,6,8,10,12].filter(v=>v<=Math.ceil(max)).map(v=>{const y=H-py-(v/max)*ih;return <g key={v}><line x1={px} x2={W-px} y1={y} y2={y} stroke="currentColor" className="text-zinc-900"/><text x="10" y={y+4} className="fill-zinc-600 text-[12px]">{v}h</text></g>})}<polyline points={pts('sleep')} fill="none" stroke="currentColor" strokeWidth="4" className="text-indigo-400"/><polyline points={pts('study')} fill="none" stroke="currentColor" strokeWidth="4" strokeDasharray="10 8" className="text-emerald-400"/>{labels.map((r,i)=>{const idx=chart.findIndex(x=>x.date===r.date),x=px+(idx/Math.max(1,chart.length-1))*iw;const d=new Date(`${r.date}T12:00:00`);return <text key={r.date} x={x} y={H-6} textAnchor="middle" className="fill-zinc-600 text-[11px]">{range>=90?d.toLocaleDateString('en-US',{month:'short'}):d.toLocaleDateString('en-US',{month:'short',day:'numeric'})}</text>})}</svg></div><div className="flex gap-5 mt-2 text-[10px] font-bold text-zinc-500"><span><i className="inline-block w-5 border-t-2 border-indigo-400 mr-2"/>Total Sleep</span><span><i className="inline-block w-5 border-t-2 border-dashed border-emerald-400 mr-2"/>Study Hours</span></div></section>
  <section className="grid md:grid-cols-3 gap-4"><div className="bg-zinc-900/50 ring-1 ring-zinc-800 rounded-2xl p-4"><div className="text-[9px] uppercase tracking-widest text-zinc-600">Today Sleep</div><div className="text-2xl font-black text-zinc-100 mt-2">{todayRow?fmt(todayRow.night_sleep_minutes+todayRow.afternoon_sleep_minutes):'—'}</div></div><div className="bg-zinc-900/50 ring-1 ring-zinc-800 rounded-2xl p-4"><div className="text-[9px] uppercase tracking-widest text-zinc-600">Today Study</div><div className="text-2xl font-black text-emerald-400 mt-2">{fmt(study[today]||0)}</div></div><div className="bg-amber-500/[0.05] ring-1 ring-amber-500/20 rounded-2xl p-4"><div className="flex items-center gap-2"><SunMedium size={14} className="text-amber-400"/><div className="text-[9px] uppercase tracking-widest text-amber-400">GATE 2027 focus</div></div><p className="text-[11px] text-zinc-500 leading-relaxed mt-2">{Math.max(0,Math.ceil((new Date('2027-02-07T00:00:00+05:30').getTime()-Date.now())/86400000))} days left. Protect consistent sleep and use the remaining time for focused study and syllabus completion.</p></div></section>
 </div></div>
}
